name: Deploy

on:
  push:
    # コミットされたブランチに基づいて、それぞれの環境にデプロイを実行する
    branches:
      - main
      - kensho
      - staging
      - koguchi
  pull_request:
    branches:
      - main
      - kensho
      - staging
      - koguchi

jobs:
  # 1. テストを実行
  tests:
    uses: ./.github/workflows/test-react.yml
  
  # 2. ビルドを実行（テスト成功後にのみ進む）
  build:
    needs: [tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

  # 3. ブランチ別にデプロイ
  # mainブランチへプッシュ時のみ動く
  deploy-main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && github.base_ref == 'main'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to main environment
        run: echo "Deploying to MAIN environment..."
        # ここにサーバーやホスティングサービスへのデプロイ処理を追加
        
  # kenshoブランチへプッシュ時のみ動く
  deploy-kensho:
    if: github.event_name == 'push' && github.ref == 'refs/heads/kensho' || github.event_name == 'pull_request' && github.base_ref == 'kensho'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to kensho environment
        run: echo "Deploying to KENSHO environment..."
        # ここにkensho用のデプロイ処理を追加

  # stagingブランチへプッシュ時のみ動く
  deploy-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging' || github.event_name == 'pull_request' && github.base_ref == 'staging'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging environment
        run: echo "Deploying to STAGING environment..."
        # ここにstaging用のデプロイ処理を追加
  
  # koguchiブランチへプッシュ時のみ動く
  deploy-koguchi:
    if: github.event_name == 'push' && github.ref == 'refs/heads/koguchi' || github.event_name == 'pull_request' && github.base_ref == 'koguchi'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to koguchi environment
        run: echo "Deploying to koguchi environment..."
        # ここにkoguchi用のデプロイ処理を追加
